### ISSUE TITLE
Web Serial is the "oldest" incubation

### ISSUE THREAD

**Issue by reillyeon** [WICG/wicg.io#27]
Depends on how you look at it. It was migrated from the WHATWG much more recently so do we count from when the repository was created or when it was adopted into the WICG?

**Comment by marcoscaceres** [comment]
The determination is simply made base on how old the repo is - but being the oldest incubation is not a bad thing or anything. The stats are just there to give us a sense of range of time.
 
In a sense, it's still accurate that it is the oldest because as long it doesn't "graduate" into a working group (or get moved back into the WICG as happened originally), it's still being actively incubated.

**Comment by reillyeon** [comment]
It probably doesn't matter, though it might be useful to have a separate data file with the history of when specs were adopted into or graduated out of the WICG.

**Comment by marcoscaceres** [comment]
closing as answered.
